// ActivityStyles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  backgroundContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 50,
  },
  metricsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  metricsGrid: {
    width: '100%',
    marginBottom: 20,
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 16,
  },
  sectionHeader: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1565C0',
    marginBottom: 24,
    marginTop: 16,
    textAlign: 'center',
    textShadowColor: 'rgba(255, 255, 255, 0.7)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    letterSpacing: 0.5,
  },
  historySection: {
    marginTop: 36,
    padding: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(200, 220, 240, 0.6)',
    shadowColor: '#1565C0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 7,
    marginHorizontal: 12,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1565C0',
    textAlign: 'center',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(21, 101, 192, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  historyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(200, 220, 240, 0.4)',
  },
  historyLabel: {
    fontSize: 17,
    color: '#555',
    fontWeight: '600',
  },
  historyValue: {
    fontSize: 17,
    color: '#1565C0',
    fontWeight: 'bold',
  },
  errorText: {
    color: '#FF3B30',
    textAlign: 'center',
    marginVertical: 16,
    fontSize: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  warningText: {
    color: '#ff6b6b',
    textAlign: 'center',
    padding: 12,
    marginBottom: 15,
    backgroundColor: 'rgba(255, 245, 245, 0.8)',
    borderRadius: 12,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  debugToggleContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  debugToggleButton: {
    backgroundColor: 'rgba(33, 150, 243, 0.15)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(200, 220, 240, 0.6)',
  },
  debugToggleText: {
    fontSize: 14,
    color: '#1565C0',
    fontWeight: '600',
  },
  debugSection: {
    backgroundColor: 'rgba(248, 249, 250, 0.85)',
    padding: 12,
    marginBottom: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(200, 220, 240, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  debugText: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    fontFamily: 'System',
  },
});

export default styles;
